server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: uv-bus
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
